"""
Obsidian JSON Canvas 1.0 Generator and Visual Knowledge Mapping Engine for Neuro.

Generates native Obsidian .canvas files from knowledge notes, topic hierarchies, or codebase dependency graphs.
Compliant with JSON Canvas 1.0 open standard (https://jsoncanvas.org/spec/1.0/).
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from pydantic import BaseModel, Field


class CanvasNode(BaseModel):
    id: str
    type: str  # 'text', 'file', 'link', 'group'
    x: int
    y: int
    width: int
    height: int
    text: str | None = None
    file: str | None = None
    url: str | None = None
    label: str | None = None
    color: str | None = None


class CanvasEdge(BaseModel):
    id: str
    fromNode: str
    toNode: str
    fromSide: str = "right"
    toSide: str = "left"
    toEnd: str = "arrow"
    label: str | None = None
    color: str | None = None


class CanvasDocument(BaseModel):
    nodes: list[dict[str, Any]] = Field(default_factory=list)
    edges: list[dict[str, Any]] = Field(default_factory=list)


class ObsidianCanvasService:
    COLOR_RED = "1"
    COLOR_ORANGE = "2"
    COLOR_YELLOW = "3"
    COLOR_GREEN = "4"
    COLOR_CYAN = "5"
    COLOR_PURPLE = "6"

    @staticmethod
    def _generate_id(content_seed: str) -> str:
        """Generates a stable 16-character hexadecimal node/edge ID."""
        return hashlib.sha256(content_seed.encode("utf-8")).hexdigest()[:16]

    @classmethod
    def create_canvas_from_notes(
        cls,
        notes: list[dict[str, Any]],
        links: list[dict[str, Any]] | None = None,
        title: str = "Neuro Knowledge Canvas",
    ) -> CanvasDocument:
        """
        Creates a structured spatial visual canvas from a set of notes and links.
        Arranges nodes in a readable grid layout with category groupings.
        """
        canvas_nodes: list[dict[str, Any]] = []
        canvas_edges: list[dict[str, Any]] = []

        # 1. Add title card node at top
        title_id = cls._generate_id(f"title:{title}")
        canvas_nodes.append(
            {
                "id": title_id,
                "type": "text",
                "text": f"# 🧠 {title}\n\n*Generated by Neuro Spatial Canvas Engine*\nTotal nodes: {len(notes)}",
                "x": 0,
                "y": -220,
                "width": 500,
                "height": 140,
                "color": cls.COLOR_PURPLE,
            }
        )

        # 2. Arrange notes into grid layout
        columns = 4
        card_width = 340
        card_height = 200
        gap_x = 80
        gap_y = 80

        node_id_to_canvas_id: dict[str, str] = {}
        for idx, note in enumerate(notes):
            orig_id = str(note.get("id", idx))
            node_title = note.get("title") or note.get("name") or f"Note {idx + 1}"
            content = note.get("content") or ""
            # Truncate content preview for card text
            preview = content[:280].strip() + ("..." if len(content) > 280 else "")
            tags = note.get("tags") or []
            tag_str = " ".join([f"#{t}" for t in tags]) if tags else ""

            card_text = f"### [[{node_title}]]\n\n{preview}\n\n{tag_str}".strip()

            col = idx % columns
            row = idx // columns
            pos_x = col * (card_width + gap_x)
            pos_y = row * (card_height + gap_y)

            cid = cls._generate_id(f"node:{orig_id}:{node_title}")
            node_id_to_canvas_id[orig_id] = cid
            node_id_to_canvas_id[node_title.strip().lower()] = cid

            # Pick color based on tags or status
            color = cls.COLOR_CYAN
            if "project" in [t.lower() for t in tags]:
                color = cls.COLOR_GREEN
            elif "important" in [t.lower() for t in tags] or "god_node" in [t.lower() for t in tags]:
                color = cls.COLOR_RED
            elif "resource" in [t.lower() for t in tags]:
                color = cls.COLOR_YELLOW

            canvas_nodes.append(
                {
                    "id": cid,
                    "type": "text",
                    "text": card_text,
                    "x": pos_x,
                    "y": pos_y,
                    "width": card_width,
                    "height": card_height,
                    "color": color,
                }
            )

        # 3. Add connecting edges
        if links:
            for link in links:
                src = str(link.get("source_id") or link.get("source") or "")
                tgt = str(link.get("target_id") or link.get("target") or "")
                rel_label = link.get("relation") or link.get("type") or None

                src_cid = node_id_to_canvas_id.get(src) or node_id_to_canvas_id.get(src.strip().lower())
                tgt_cid = node_id_to_canvas_id.get(tgt) or node_id_to_canvas_id.get(tgt.strip().lower())

                if src_cid and tgt_cid and src_cid != tgt_cid:
                    edge_id = cls._generate_id(f"edge:{src_cid}->{tgt_cid}:{rel_label}")
                    canvas_edges.append(
                        {
                            "id": edge_id,
                            "fromNode": src_cid,
                            "toNode": tgt_cid,
                            "fromSide": "right",
                            "toSide": "left",
                            "toEnd": "arrow",
                            "label": rel_label,
                        }
                    )

        return CanvasDocument(nodes=canvas_nodes, edges=canvas_edges)

    @classmethod
    def create_canvas_from_roadmap(
        cls,
        goal: str,
        prerequisite_nodes: list[dict[str, Any]],
        unlock_nodes: list[dict[str, Any]],
    ) -> CanvasDocument:
        """
        Generates an Obsidian Canvas learning tree map for a target skill or topic.
        """
        canvas_nodes: list[dict[str, Any]] = []
        canvas_edges: list[dict[str, Any]] = []

        # Target Goal Central Node
        target_id = cls._generate_id(f"target:{goal}")
        canvas_nodes.append(
            {
                "id": target_id,
                "type": "text",
                "text": f"# 🎯 Target Goal: {goal}\n\n*Central Mastery Milestone*",
                "x": 600,
                "y": 200,
                "width": 380,
                "height": 180,
                "color": cls.COLOR_PURPLE,
            }
        )

        # Left Column: Prerequisites (inflow to target)
        card_width = 320
        card_height = 150
        gap_y = 40

        for idx, prereq in enumerate(prerequisite_nodes):
            p_id = cls._generate_id(f"prereq:{prereq.get('id')}:{idx}")
            title = prereq.get("title") or prereq.get("name") or "Prerequisite"
            status = prereq.get("status", "not_started")
            zone = prereq.get("zone", "Foundations")

            pos_x = 100
            pos_y = idx * (card_height + gap_y)

            color = cls.COLOR_GREEN if status == "completed" else cls.COLOR_ORANGE

            canvas_nodes.append(
                {
                    "id": p_id,
                    "type": "text",
                    "text": f"### 📌 [[{title}]]\n**Zone:** {zone}\n**Status:** `{status}`",
                    "x": pos_x,
                    "y": pos_y,
                    "width": card_width,
                    "height": card_height,
                    "color": color,
                }
            )

            # Edge to target
            edge_id = cls._generate_id(f"edge:{p_id}->{target_id}")
            canvas_edges.append(
                {
                    "id": edge_id,
                    "fromNode": p_id,
                    "toNode": target_id,
                    "fromSide": "right",
                    "toSide": "left",
                    "toEnd": "arrow",
                    "label": "requires",
                }
            )

        # Right Column: Unlocked Superpowers (outflow from target)
        for idx, unlock in enumerate(unlock_nodes):
            u_id = cls._generate_id(f"unlock:{unlock.get('id')}:{idx}")
            title = unlock.get("title") or unlock.get("name") or "Unlocked Skill"
            zone = unlock.get("zone", "Advanced Mastery")

            pos_x = 1100
            pos_y = idx * (card_height + gap_y)

            canvas_nodes.append(
                {
                    "id": u_id,
                    "type": "text",
                    "text": f"### 🚀 [[{title}]]\n**Unlocked Milestone**\n**Zone:** {zone}",
                    "x": pos_x,
                    "y": pos_y,
                    "width": card_width,
                    "height": card_height,
                    "color": cls.COLOR_CYAN,
                }
            )

            # Edge from target
            edge_id = cls._generate_id(f"edge:{target_id}->{u_id}")
            canvas_edges.append(
                {
                    "id": edge_id,
                    "fromNode": target_id,
                    "toNode": u_id,
                    "fromSide": "right",
                    "toSide": "left",
                    "toEnd": "arrow",
                    "label": "unlocks",
                }
            )

        return CanvasDocument(nodes=canvas_nodes, edges=canvas_edges)

    @staticmethod
    def to_json(canvas_doc: CanvasDocument, indent: int = 2) -> str:
        """Serializes CanvasDocument to formatted JSON Canvas string."""
        return json.dumps(canvas_doc.model_dump(), indent=indent)
