"""initial_schema

Revision ID: 24bc08a86aa7
Revises:
Create Date: 2026-07-23 17:14:52.536783

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24bc08a86aa7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("syncblob", sa.Column("iv", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("syncblob", sa.Column("salt", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("syncblob", sa.Column("sequence_number", sa.Integer(), nullable=False, server_default="1"))
    op.add_column("syncblob", sa.Column("device_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_syncblob_sequence_number"), "syncblob", ["sequence_number"], unique=False)
    op.create_foreign_key(None, "syncblob", "devicekey", ["device_id"], ["id"])
    op.add_column("task", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_task_user_id"), "task", ["user_id"], unique=False)
    op.create_foreign_key(None, "task", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_index(op.f("ix_task_user_id"), table_name="task")
    op.drop_column("task", "user_id")
    op.drop_constraint(None, "syncblob", type_="foreignkey")
    op.drop_index(op.f("ix_syncblob_sequence_number"), table_name="syncblob")
    op.drop_column("syncblob", "device_id")
    op.drop_column("syncblob", "sequence_number")
    op.drop_column("syncblob", "salt")
    op.drop_column("syncblob", "iv")
    # ### end Alembic commands ###
